from library.hashtable.hashchaining import hashchaining
ht = hashchaining(20)
ht.put("Prateek",34)
ht.put("Aditi",23)
ht.put("Aditi2",12)
ht.put("Aditi23",13)
ht.put("Somya",21)
ht.put("Sonal",123)
ht.put("Aditi",122)
print(ht.get("Aditi"))
print(ht.get("Somya"))
ht.remove("Aditi")
ht.remove("Somya")
ht.print()
print("Helllo")